# Generated by Django 5.2.4 on 2025-08-01 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('provider_id', models.AutoField(primary_key=True, serialize=False)),
                ('npi', models.CharField(max_length=20, unique=True)),
                ('address_line_1', models.CharField(blank=True, max_length=255, null=True)),
                ('address_line_2', models.CharField(blank=True, max_length=255, null=True)),
                ('city_name', models.CharField(blank=True, default='unknown', max_length=255, null=True)),
                ('state_name', models.CharField(blank=True, default='unknown', max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, default='US', max_length=5, null=True)),
                ('telephone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('telephone_extension', models.CharField(blank=True, max_length=10, null=True)),
                ('fax_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('taxonomy_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('classification', models.CharField(max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProviderTaxonomy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaid_providers_lookup.provider')),
                ('taxonomy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicaid_providers_lookup.taxonomy')),
            ],
            options={
                'unique_together': {('provider', 'taxonomy')},
            },
        ),
    ]
