# Generated by Django 5.2.4 on 2025-08-01 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaid_providers_lookup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='npi',
            field=models.CharField(max_length=20),
        ),
    ]
