# Generated by Django 5.2.4 on 2025-08-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaid_providers_lookup', '0002_alter_provider_npi'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='first_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='provider',
            name='last_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
