# Generated by Django 5.2.4 on 2025-08-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaid_providers_lookup', '0003_provider_first_name_provider_last_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='providertaxonomy',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='providertaxonomy',
            name='primary_switch',
            field=models.CharField(default='N', max_length=1),
        ),
        migrations.AlterUniqueTogether(
            name='providertaxonomy',
            unique_together={('provider', 'taxonomy', 'primary_switch')},
        ),
    ]
