# Generated by Django 5.2.4 on 2025-08-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicaid_providers_lookup', '0004_alter_providertaxonomy_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providertaxonomy',
            name='primary_switch',
            field=models.CharField(blank=True, default='N', max_length=1, null=True),
        ),
    ]
